- name: Reset K8S Cluster
  hosts: dbs
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml
  vars:
    minimal_ansible_version: 2.7.0
  tasks:
    - name: Checking ansible version
      fail:
        msg: "Ansible version must be {{ minimal_ansible_version }} or higher"
      when: ansible_version.full is version(minimal_ansible_version, '<')

    - name: Stop services
      ansible.builtin.systemd:
        name: "etcd"
        state: stopped

    - name: Stop services
      ansible.builtin.systemd:
        name: "patroni"
        state: stopped

    - name: Stop services
      ansible.builtin.systemd:
        name: "postgresql"
        state: stopped


    - name: Remove configuration files
      ansible.builtin.file:
        path: /etc/default/etcd
        state: absent

    - name: Remove configuration files
      ansible.builtin.file:
        path: /etc/patroni/config.yml
        state: absent
     


    - name: Remove configuration files
      ansible.builtin.file:
        path: /etc/patroni/patroni.yml
        state: absent

    - name: Remove configuration files
      ansible.builtin.file:
        path: /var/lib/etcd
        state: absent


    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /var/lib/etcd
        state: directory        
        owner: etcd
        group: etcd

      
    - name: Remove configuration files
      ansible.builtin.file:
        path: /data/patroni
        state: absent
      