- hosts: dbs 
  vars_files:
    - ../vars/main.yml
  tasks:     

  # - name: Check clusters
  #   shell: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"


  # - name: Add specified repository into sources list
  #   ansible.builtin.apt_repository:
  #     repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
  #     state: present
  #     filename: pgdg.list

  - name: Update repositories cache
    apt:      
      update_cache: yes


  - name: Install postgresql server packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages: 
      - postgresql-12
      - postgresql-server-dev-12
  
  - name: Stop service postgrsql on debian, if running
    ansible.builtin.systemd:
      name: postgresql
      state: stopped


  - name: Check clusters
    shell: "pg_lsclusters"
    register: clusters

  - name: Remove default cluster
    shell: "pg_dropcluster 12 main"
    when: "'12  main' in clusters"

  - name: Check bin files exist
    stat: 
      path: /usr/sbin/initdb
    register: bincheck

  - name: Links bin files 
    shell: "sudo ln -s /usr/lib/postgresql/12/bin/* /usr/sbin/"
    when: not bincheck.stat.exists


  - name: Add timescale repository into sources list using specified filename
    ansible.builtin.apt_repository:
      repo: ppa:timescale/timescaledb-ppa
      state: present
      filename: timescaledb


  - name: Update repositories cache and install "timescaledb" package
    apt:
      name: timescaledb-postgresql-12
      update_cache: yes


  # - name: Check clusters
  #   shell: "chown postgres.postgres /data"
  #   register: clusters

